### ISSUE TITLE
Cannot find module 'fs/promises' when running Azure Pipelines pool agent

### ISSUE THREAD

**Issue by mangan77** [qetza/replacetokens-task#61]
Hi,

I'm having trouble running the task using an Azure Pipelines agent. The task fails with the message "Cannot find module 'fs/promises'". 

I've tried to install Node 16 before the ReplaceTokens task run, but the agent refers to it being installed already (16.20.2). 

```
##[error]Unhandled: Cannot find module 'fs/promises'
##[error]Error: Cannot find module 'fs/promises'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.3292 (/home/vsts/work/_tasks/replacetokens_a8515ec8-7254-4ffd-912c-86772e2b5962/6.0.6/index.js:55520:18)
    at __nccwpck_require__ (/home/vsts/work/_tasks/replacetokens_a8515ec8-7254-4ffd-912c-86772e2b5962/6.0.6/index.js:60077:43)
    at Object.9430 (/home/vsts/work/_tasks/replacetokens_a8515ec8-7254-4ffd-912c-86772e2b5962/6.0.6/index.js:13641:25)
    at __nccwpck_require__ (/home/vsts/work/_tasks/replacetokens_a8515ec8-7254-4ffd-912c-86772e2b5962/6.0.6/index.js:60077:43)
    at Object.257 (/home/vsts/work/_tasks/replacetokens_a8515ec8-7254-4ffd-912c-86772e2b5962/6.0.6/index.js:176:12)
    at __nccwpck_require__ (/home/vsts/work/_tasks/replacetokens_a8515ec8-7254-4ffd-912c-86772e2b5962/6.0.6/index.js:60077:43)
```

Task data:
```
Task         : Replace Tokens
Description  : Replace tokens in text based files
Version      : 6.0.6
Author       : Guillaume ROUCHON
Help         : [Learn more about this task](https://github.com/qetza/replacetokens-task/blob/master/tasks/ReplaceTokensV6/README.md) (v6.0.6)
```

Build agent data (ubuntu-latest):
```
Agent name: 'Azure Pipelines 4'
Agent machine name: 'fv-az470-467'
Current agent version: '3.245.0'
Operating System
Runner Image
Runner Image Provisioner
Current image version: '20241006.1.0'
Agent running as: 'vsts'
Prepare build directory.
Set build variables.
Download all required tasks.
Downloading task: DownloadPipelineArtifact (1.230.0)
Downloading task: NodeTaskRunnerInstaller (0.246.1)
Downloading task: replacetokens (6.0.6)
Checking job knob settings.
   Knob: DockerActionRetries = true Source: $(VSTSAGENT_DOCKER_ACTION_RETRIES) 
   Knob: AgentToolsDirectory = /opt/hostedtoolcache Source: ${AGENT_TOOLSDIRECTORY} 
   Knob: UseGitLongPaths = true Source: $(USE_GIT_LONG_PATHS) 
   Knob: UseNode10 = true Source: $(AGENT_USE_NODE10) 
   Knob: AgentPerflog = /home/vsts/perflog Source: ${VSTS_AGENT_PERFLOG} 
   Knob: EnableIssueSourceValidation = true Source: $(ENABLE_ISSUE_SOURCE_VALIDATION) 
   Knob: AgentEnablePipelineArtifactLargeChunkSize = true Source: $(AGENT_ENABLE_PIPELINEARTIFACT_LARGE_CHUNK_SIZE) 
   Knob: ContinueAfterCancelProcessTreeKillAttempt = true Source: 
$(VSTSAGENT_CONTINUE_AFTER_CANCEL_PROCESSTREEKILL_ATTEMPT) 
   Knob: ProcessHandlerSecureArguments = false Source: $(AZP_75787_ENABLE_NEW_LOGIC) 
   Knob: ProcessHandlerSecureArguments = false Source: $(AZP_75787_ENABLE_NEW_LOGIC_LOG) 
   Knob: ProcessHandlerTelemetry = true Source: $(AZP_75787_ENABLE_COLLECT) 
   Knob: UseNewNodeHandlerTelemetry = True Source: $(DistributedTask.Agent.USENEWNODEHANDLERTELEMETRY) 
   Knob: ProcessHandlerEnableNewLogic = true Source: $(AZP_75787_ENABLE_NEW_PH_LOGIC) 
   Knob: EnableResourceMonitorDebugOutput = true Source: $(AZP_ENABLE_RESOURCE_MONITOR_DEBUG_OUTPUT) 
   Knob: EnableResourceUtilizationWarnings = true Source: $(AZP_ENABLE_RESOURCE_UTILIZATION_WARNINGS) 
   Knob: IgnoreVSTSTaskLib = true Source: $(AZP_AGENT_IGNORE_VSTSTASKLIB) 
   Knob: FailJobWhenAgentDies = true Source: $(FAIL_JOB_WHEN_AGENT_DIES) 
   Knob: CheckForTaskDeprecation = true Source: $(AZP_AGENT_CHECK_FOR_TASK_DEPRECATION) 
   Knob: CheckIfTaskNodeRunnerIsDeprecated = False Source: $(DistributedTask.Agent.CheckIfTaskNodeRunnerIsDeprecated) 
   Knob: LogTaskNameInUserAgent = true Source: $(AZP_AGENT_LOG_TASKNAME_IN_USERAGENT) 
   Knob: UseFetchFilterInCheckoutTask = true Source: $(AGENT_USE_FETCH_FILTER_IN_CHECKOUT_TASK) 
   Knob: Rosetta2Warning = true Source: $(ROSETTA2_WARNING) 
   Knob: AddForceCredentialsToGitCheckout = True Source: $(DistributedTask.Agent.AddForceCredentialsToGitCheckout) 
Finished checking job knob settings.
Start tracking orphan processes.
```

Update: Formatting

**Comment by mangan77** [comment]
Turns out someone set the pipeline variable `AGENT_USE_NODE10` to `true`.
